//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rights {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rights() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAS.Common.Properties.Rights", typeof(Rights).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media - archive.
        /// </summary>
        public static string EngineRight_MediaArchive {
            get {
                return ResourceManager.GetString("EngineRight_MediaArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media - delete.
        /// </summary>
        public static string EngineRight_MediaDelete {
            get {
                return ResourceManager.GetString("EngineRight_MediaDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media - properties edit.
        /// </summary>
        public static string EngineRight_MediaEdit {
            get {
                return ResourceManager.GetString("EngineRight_MediaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media - export.
        /// </summary>
        public static string EngineRight_MediaExport {
            get {
                return ResourceManager.GetString("EngineRight_MediaExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media - ingest.
        /// </summary>
        public static string EngineRight_MediaIngest {
            get {
                return ResourceManager.GetString("EngineRight_MediaIngest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play rundowns.
        /// </summary>
        public static string EngineRight_Play {
            get {
                return ResourceManager.GetString("EngineRight_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview on channel.
        /// </summary>
        public static string EngineRight_Preview {
            get {
                return ResourceManager.GetString("EngineRight_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rundowns - full edit access.
        /// </summary>
        public static string EngineRight_Rundown {
            get {
                return ResourceManager.GetString("EngineRight_Rundown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string EventRight_Create {
            get {
                return ResourceManager.GetString("EventRight_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string EventRight_Delete {
            get {
                return ResourceManager.GetString("EventRight_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string EventRight_Modify {
            get {
                return ResourceManager.GetString("EventRight_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string IngestFolderRight_Export {
            get {
                return ResourceManager.GetString("IngestFolderRight_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingest.
        /// </summary>
        public static string IngestFolderRight_Ingest {
            get {
                return ResourceManager.GetString("IngestFolderRight_Ingest", resourceCulture);
            }
        }
    }
}
