//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS.Client.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAS.Client.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string _caption_Confirmation {
            get {
                return ResourceManager.GetString("_caption_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string _caption_Error {
            get {
                return ResourceManager.GetString("_caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed. Following error occurred:
        ///{0}.
        /// </summary>
        public static string _message_CommandFailed {
            get {
                return ResourceManager.GetString("_message_CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0} items more.
        /// </summary>
        public static string _moreItems {
            get {
                return ResourceManager.GetString("_moreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete: {0}:{1}.
        /// </summary>
        public static string _title_Delete {
            get {
                return ResourceManager.GetString("_title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string _title_Duration {
            get {
                return ResourceManager.GetString("_title_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty clip.
        /// </summary>
        public static string _title_EmptyMovie {
            get {
                return ResourceManager.GetString("_title_EmptyMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0} -&gt; {1}.
        /// </summary>
        public static string _title_ExportClip {
            get {
                return ResourceManager.GetString("_title_ExportClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure LUFS: {0}:{1}.
        /// </summary>
        public static string _title_MeasureVolume {
            get {
                return ResourceManager.GetString("_title_MeasureVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string _title_NewContainer {
            get {
                return ResourceManager.GetString("_title_NewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New directory.
        /// </summary>
        public static string _title_NewDirectory {
            get {
                return ResourceManager.GetString("_title_NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New live.
        /// </summary>
        public static string _title_NewLive {
            get {
                return ResourceManager.GetString("_title_NewLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New rundown.
        /// </summary>
        public static string _title_NewRundown {
            get {
                return ResourceManager.GetString("_title_NewRundown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string _title_NewSegment {
            get {
                return ResourceManager.GetString("_title_NewSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of rundown.
        /// </summary>
        public static string _title_RundownEnd {
            get {
                return ResourceManager.GetString("_title_RundownEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment name.
        /// </summary>
        public static string _title_SegmentName {
            get {
                return ResourceManager.GetString("_title_SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC In.
        /// </summary>
        public static string _title_TCIn {
            get {
                return ResourceManager.GetString("_title_TCIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Out.
        /// </summary>
        public static string _title_TCOut {
            get {
                return ResourceManager.GetString("_title_TCOut", resourceCulture);
            }
        }
    }
}
