//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS.Client.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAS.Client.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string _all_ {
            get {
                return ResourceManager.GetString("_all_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string _allFiles {
            get {
                return ResourceManager.GetString("_allFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animations (main).
        /// </summary>
        public static string _animations_Primary {
            get {
                return ResourceManager.GetString("_animations_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animations (backup).
        /// </summary>
        public static string _animations_Secondary {
            get {
                return ResourceManager.GetString("_animations_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string _archive {
            get {
                return ResourceManager.GetString("_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string _button_Cancel {
            get {
                return ResourceManager.GetString("_button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string _button_Ok {
            get {
                return ResourceManager.GetString("_button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string _caption_Confirmation {
            get {
                return ResourceManager.GetString("_caption_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string _caption_Error {
            get {
                return ResourceManager.GetString("_caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual source control.
        /// </summary>
        public static string _caption_Switcher {
            get {
                return ResourceManager.GetString("_caption_Switcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string _caption_Warning {
            get {
                return ResourceManager.GetString("_caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string _media {
            get {
                return ResourceManager.GetString("_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string _mediaOperation_Copy {
            get {
                return ResourceManager.GetString("_mediaOperation_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string _mediaOperation_Delete {
            get {
                return ResourceManager.GetString("_mediaOperation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string _mediaOperation_Export {
            get {
                return ResourceManager.GetString("_mediaOperation_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingest.
        /// </summary>
        public static string _mediaOperation_Ingest {
            get {
                return ResourceManager.GetString("_mediaOperation_Ingest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudness.
        /// </summary>
        public static string _mediaOperation_Loudness {
            get {
                return ResourceManager.GetString("_mediaOperation_Loudness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string _mediaOperation_Move {
            get {
                return ResourceManager.GetString("_mediaOperation_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot initialize application because of error: 
        ///{0}.
        /// </summary>
        public static string _message_CantInitializeApplication {
            get {
                return ResourceManager.GetString("_message_CantInitializeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot initialize engines because of error: 
        ///{0}
        ///Use TVPlay.config program to configure the system..
        /// </summary>
        public static string _message_CantInitializeEngines {
            get {
                return ResourceManager.GetString("_message_CantInitializeEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed. Following error occurred:
        ///{0}.
        /// </summary>
        public static string _message_CommandFailed {
            get {
                return ResourceManager.GetString("_message_CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database update is required to run the application.
        ///Backup is strongly recommended.
        ///
        ///Proceed with update?.
        /// </summary>
        public static string _message_DatabaseUpdateRequired {
            get {
                return ResourceManager.GetString("_message_DatabaseUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete anyway?.
        /// </summary>
        public static string _message_DeleteAnyway {
            get {
                return ResourceManager.GetString("_message_DeleteAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to refresh directory. Following error occurred:
        ///{0}.
        /// </summary>
        public static string _message_DirectoryRefreshFailed {
            get {
                return ResourceManager.GetString("_message_DirectoryRefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient user rights to delete media.
        /// </summary>
        public static string _message_MediaDeleteResult_InsufficientRights {
            get {
                return ResourceManager.GetString("_message_MediaDeleteResult_InsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete not allowed due to following reason(s):.
        /// </summary>
        public static string _message_MediaDeleteResult_NotAllowed {
            get {
                return ResourceManager.GetString("_message_MediaDeleteResult_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media is delete-protected.
        /// </summary>
        public static string _message_MediaDeleteResult_Protected {
            get {
                return ResourceManager.GetString("_message_MediaDeleteResult_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is scheduled in {0} at {1}.
        /// </summary>
        public static string _message_MediaDeleteResult_Scheduled {
            get {
                return ResourceManager.GetString("_message_MediaDeleteResult_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown reason.
        /// </summary>
        public static string _message_MediaDeleteResult_Unknown {
            get {
                return ResourceManager.GetString("_message_MediaDeleteResult_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0} items more.
        /// </summary>
        public static string _moreItems {
            get {
                return ResourceManager.GetString("_moreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string _none_ {
            get {
                return ResourceManager.GetString("_none_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        public static string _or_ {
            get {
                return ResourceManager.GetString("_or_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string _primary {
            get {
                return ResourceManager.GetString("_primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abadon changes in {0}?.
        /// </summary>
        public static string _query_AbadonChanges {
            get {
                return ResourceManager.GetString("_query_AbadonChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} clients. This will abort their work.
        ///Really exit?.
        /// </summary>
        public static string _query_ClientsConnectedOnExit {
            get {
                return ResourceManager.GetString("_query_ClientsConnectedOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all graphics elements of this item?.
        /// </summary>
        public static string _query_DeleteAllGraphics {
            get {
                return ResourceManager.GetString("_query_DeleteAllGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item with all subitems?.
        /// </summary>
        public static string _query_DeleteItem {
            get {
                return ResourceManager.GetString("_query_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items ({0})?
        ///{1}.
        /// </summary>
        public static string _query_DeleteSelected {
            get {
                return ResourceManager.GetString("_query_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to delete:
        ///{0}
        ///
        ///Really delete?.
        /// </summary>
        public static string _query_DeleteSelectedFiles {
            get {
                return ResourceManager.GetString("_query_DeleteSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really exit application?.
        /// </summary>
        public static string _query_ExitApplication {
            get {
                return ResourceManager.GetString("_query_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really load this item now?.
        /// </summary>
        public static string _query_LoadWhileRunning {
            get {
                return ResourceManager.GetString("_query_LoadWhileRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really play this item now?.
        /// </summary>
        public static string _query_PlayWhileRunning {
            get {
                return ResourceManager.GetString("_query_PlayWhileRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save modified data about {0}?.
        /// </summary>
        public static string _query_SaveChangedData {
            get {
                return ResourceManager.GetString("_query_SaveChangedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application should execute in one instance only, but was running already.
        ///Really start new one?.
        /// </summary>
        public static string _query_StartAnotherInstance {
            get {
                return ResourceManager.GetString("_query_StartAnotherInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is configured as backup for another installation and should be executing ONLY when that instance cannot operate.
        ///Simultaneous operation of the two instances is not permitted.
        ///Do you really want to run this BACKUP play-out?.
        /// </summary>
        public static string _query_StartBackupInstance {
            get {
                return ResourceManager.GetString("_query_StartBackupInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really undelete?.
        /// </summary>
        public static string _query_Undelete {
            get {
                return ResourceManager.GetString("_query_Undelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rundown.
        /// </summary>
        public static string _rundown {
            get {
                return ResourceManager.GetString("_rundown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rundowns.
        /// </summary>
        public static string _rundowns {
            get {
                return ResourceManager.GetString("_rundowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string _secondary {
            get {
                return ResourceManager.GetString("_secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete: {0}:{1}.
        /// </summary>
        public static string _title_Delete {
            get {
                return ResourceManager.GetString("_title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string _title_Duration {
            get {
                return ResourceManager.GetString("_title_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty clip.
        /// </summary>
        public static string _title_EmptyMovie {
            get {
                return ResourceManager.GetString("_title_EmptyMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0} -&gt; {1}.
        /// </summary>
        public static string _title_ExportClip {
            get {
                return ResourceManager.GetString("_title_ExportClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure LUFS: {0}:{1}.
        /// </summary>
        public static string _title_MeasureVolume {
            get {
                return ResourceManager.GetString("_title_MeasureVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string _title_NewCommandScript {
            get {
                return ResourceManager.GetString("_title_NewCommandScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string _title_NewContainer {
            get {
                return ResourceManager.GetString("_title_NewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New directory.
        /// </summary>
        public static string _title_NewDirectory {
            get {
                return ResourceManager.GetString("_title_NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New live.
        /// </summary>
        public static string _title_NewLive {
            get {
                return ResourceManager.GetString("_title_NewLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New rundown.
        /// </summary>
        public static string _title_NewRundown {
            get {
                return ResourceManager.GetString("_title_NewRundown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string _title_NewSegment {
            get {
                return ResourceManager.GetString("_title_NewSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of rundown.
        /// </summary>
        public static string _title_RundownEnd {
            get {
                return ResourceManager.GetString("_title_RundownEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment name.
        /// </summary>
        public static string _title_SegmentName {
            get {
                return ResourceManager.GetString("_title_SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC In.
        /// </summary>
        public static string _title_TCIn {
            get {
                return ResourceManager.GetString("_title_TCIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Out.
        /// </summary>
        public static string _title_TCOut {
            get {
                return ResourceManager.GetString("_title_TCOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file....
        /// </summary>
        public static string _tooltip_SelectFile {
            get {
                return ResourceManager.GetString("_tooltip_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string _unknown_ {
            get {
                return ResourceManager.GetString("_unknown_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command.
        /// </summary>
        public static string _validate_CommandSyntax {
            get {
                return ResourceManager.GetString("_validate_CommandSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (considering start TC) is longer than clip..
        /// </summary>
        public static string _validate_DurationInvalid {
            get {
                return ResourceManager.GetString("_validate_DurationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End timecode is behind end of clip (clip ends at {0})..
        /// </summary>
        public static string _validate_EndTCAfterFile {
            get {
                return ResourceManager.GetString("_validate_EndTCAfterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End timecode is before start of clip (clip starts at {0})..
        /// </summary>
        public static string _validate_EndTCBeforeFile {
            get {
                return ResourceManager.GetString("_validate_EndTCBeforeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File of this name already exists..
        /// </summary>
        public static string _validate_FileAlreadyExists {
            get {
                return ResourceManager.GetString("_validate_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must have extension {0}..
        /// </summary>
        public static string _validate_FileMustHaveExtension {
            get {
                return ResourceManager.GetString("_validate_FileMustHaveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name can&apos;t contain special characters..
        /// </summary>
        public static string _validate_FileNameCanNotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("_validate_FileNameCanNotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name can&apos;t start or end with space..
        /// </summary>
        public static string _validate_FileNameCanNotStartOrEndWithSpace {
            get {
                return ResourceManager.GetString("_validate_FileNameCanNotStartOrEndWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to provide a valid file name..
        /// </summary>
        public static string _validate_FileNameEmpty {
            get {
                return ResourceManager.GetString("_validate_FileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid video format..
        /// </summary>
        public static string _validate_InvalidVideoFormat {
            get {
                return ResourceManager.GetString("_validate_InvalidVideoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of duration and start delay exceeds item length..
        /// </summary>
        public static string _validate_ScheduledDelayInvalid {
            get {
                return ResourceManager.GetString("_validate_ScheduledDelayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timecode is behind end of clip (clip ends at {0})..
        /// </summary>
        public static string _validate_StartTCAfterFile {
            get {
                return ResourceManager.GetString("_validate_StartTCAfterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timecode is before start of clip (clip starts at {0})..
        /// </summary>
        public static string _validate_StartTCBeforeFile {
            get {
                return ResourceManager.GetString("_validate_StartTCBeforeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time passed..
        /// </summary>
        public static string _validate_StartTimePassed {
            get {
                return ResourceManager.GetString("_validate_StartTimePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered text is too long..
        /// </summary>
        public static string _validate_TextTooLong {
            get {
                return ResourceManager.GetString("_validate_TextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition pause cannot be longer than transition itself..
        /// </summary>
        public static string _validate_TransitionPauseTimeInvalid {
            get {
                return ResourceManager.GetString("_validate_TransitionPauseTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition time exceeds clip duration..
        /// </summary>
        public static string _validate_TransitionTimeInvalid {
            get {
                return ResourceManager.GetString("_validate_TransitionTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all recording informations..
        /// </summary>
        public static string _validateRecordingInfo {
            get {
                return ResourceManager.GetString("_validateRecordingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of play must be between start and end clip timecode..
        /// </summary>
        public static string _validateStartPlayMustBeInsideFile {
            get {
                return ResourceManager.GetString("_validateStartPlayMustBeInsideFile", resourceCulture);
            }
        }
    }
}
