//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAS.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string _all_ {
            get {
                return ResourceManager.GetString("_all_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string _button_Add {
            get {
                return ResourceManager.GetString("_button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0} items more.
        /// </summary>
        internal static string _moreItems {
            get {
                return ResourceManager.GetString("_moreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string _none_ {
            get {
                return ResourceManager.GetString("_none_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        internal static string _or_ {
            get {
                return ResourceManager.GetString("_or_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all graphics elements of this item?.
        /// </summary>
        internal static string _query_DeleteAllGraphics {
            get {
                return ResourceManager.GetString("_query_DeleteAllGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item with all subitems?.
        /// </summary>
        internal static string _query_DeleteItem {
            get {
                return ResourceManager.GetString("_query_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items ({0})?
        ///{1}.
        /// </summary>
        internal static string _query_DeleteSelected {
            get {
                return ResourceManager.GetString("_query_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are deleting following {0} container(s):
        ///{1}
        ///Are you sure?.
        /// </summary>
        internal static string _query_DeleteSelectedContainers {
            get {
                return ResourceManager.GetString("_query_DeleteSelectedContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to delete:
        ///{0}
        ///
        ///Really delete?.
        /// </summary>
        internal static string _query_DeleteSelectedFiles {
            get {
                return ResourceManager.GetString("_query_DeleteSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really exit application?.
        /// </summary>
        internal static string _query_ExitApplication {
            get {
                return ResourceManager.GetString("_query_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save modified data?.
        /// </summary>
        internal static string _query_SaveChangedData {
            get {
                return ResourceManager.GetString("_query_SaveChangedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application should execute in one instance only, but was running already.
        ///Really start new one?.
        /// </summary>
        internal static string _query_StartAnotherInstance {
            get {
                return ResourceManager.GetString("_query_StartAnotherInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (considring start TC) is longer than clip.
        /// </summary>
        internal static string _validate_DurationInvalid {
            get {
                return ResourceManager.GetString("_validate_DurationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File of this name already exists.
        /// </summary>
        internal static string _validate_FileAlreadyExists {
            get {
                return ResourceManager.GetString("_validate_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must have extension {0}.
        /// </summary>
        internal static string _validate_FileMustHaveExtension {
            get {
                return ResourceManager.GetString("_validate_FileMustHaveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name can&apos;t contain special characters.
        /// </summary>
        internal static string _validate_FileNameCanNotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("_validate_FileNameCanNotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timecode is behind end of clip (clip ends at {0}).
        /// </summary>
        internal static string _validate_StartTCAfterFile {
            get {
                return ResourceManager.GetString("_validate_StartTCAfterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timecode is before start of clip (clip starts at {0}).
        /// </summary>
        internal static string _validate_StartTCBeforeFile {
            get {
                return ResourceManager.GetString("_validate_StartTCBeforeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time passed.
        /// </summary>
        internal static string _validate_StartTimePassed {
            get {
                return ResourceManager.GetString("_validate_StartTimePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition time exceeds clip duration.
        /// </summary>
        internal static string _validate_TransitionTimeInvalid {
            get {
                return ResourceManager.GetString("_validate_TransitionTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of play must be between start and end clip timecode.
        /// </summary>
        internal static string _validateStartPlayMustBeInsideFile {
            get {
                return ResourceManager.GetString("_validateStartPlayMustBeInsideFile", resourceCulture);
            }
        }
    }
}
